use assignments;

select * from fact;
select * from Location;
select * from Product;

--1. Display the number of states present in the LocationTable
select count(distinct state) as NunOfStates from Location; --dont forget to use distinct, count just counts the number of rows in total

--2.How many products are of regular type?
select count(*) as NumOfRegProducts from Product where Type='Regular';

--3.How much spending has been done on marketing of product ID 1?
select sum(Marketing) as totalMarketingSpend from fact where ProductId = 1;

--4. What is the minimum sales of a product?
select min(sales) as minsales from fact

--5. Display the max Cost of Good Sold (COGS).
select max(COGS) as Maxcogs from fact

--6. Display the details of the product where product type is coffee. 
select * from Product where Product_Type = 'Coffee'

--7. Display the details where total expenses are greater than 40.
select * from fact where total_expenses > 40

--8. What is the average sales in area code 719?
select avg(Sales) as avgsales from fact where Area_Code = '719'

--9. Find out the total profit generated by Colorado state.
select Sum(profit) as Coloradoprofit from fact f full outer join Location l
on f.area_code = l.Area_Code where State = 'Colorado'

--10. Display the average inventory for each product ID.
select ProductId, avg(Inventory) as avginventory --if you join tbales when its not needed, it will throw error so dont do it
from fact f 
group by ProductId
order by productid asc

--11. Display state in a sequential order in a Location Table.
select distinct state from location order by state asc;

--12. Display the average budget Margin of the Product where the average budget margin should be greater than 100.
select ProductId, avg(Budget_Margin) as avgMAR from fact
group by productid --since grouping and aggregation(finding average in this case) are involved, you cant use 'where', you need to use 'having'
having avg(Budget_Margin) > 100 --SQL executes the having clause first and then allots the alias name to it, so use the calculation instead of avgMAR while calling having clause

--13. What is the total sales done on date 2010-01-01?
select sum(sales) as total_sales from fact
where date='2010-01-01' --HERE where filters out the columns first and then the summation is done on that filter

--14. Display the average total expense of each product ID on an individual date.
select date,productid, avg(total_expenses) as averagetotexp from fact
group by date,productid
order by date,productid asc

--15. Display the table with the following attributes such as date, productID, product_type, product, sales, profit, state, area_code.
select f.date, 
       f.productID, 
	   p.product_type, 
	   p.product, 
	   f.sales, 
	   f.profit, 
	   l.state, 
	   f.area_code --wherever its possible to put f, put f
from fact f
join product p on f.productid=p.productid
join location l on f.area_code=l.area_code

--16. Display the rank without any gap to show the sales wise rank.
select *,dense_RANK() over (Order by Sales desc) as rank_sales from fact --dense_rank() gives the same rank to two different rows if they have same sales in this case

--17. Find the state wise profit and sales.
select 
     l.state, --cant use distint with l. so use group by
	 sum(f.profit) as totalprofit,
	 sum(f.sales) as totalsales
from fact f join location l on f.area_code=l.area_code
group by l.state

--18. Find the state wise profit and sales along with the productname.
select
     l.state,
	 p.product,
	 sum(f.profit) as totalprofit,
	 sum(f.sales) as totalsales
from fact f 
join location l on f.area_code=l.area_code
join product p on f.productid = p.productid
group by l.state,p.product
order by totalsales desc,totalprofit desc

--19. If there is an increase in sales of 5%, calculate the increasedsales.
select sales, sales*1.05 as increased_sales from fact


--20. Find the maximum profit along with the product ID and producttype. 

select fact.ProductId,Product_Type,max(Profit) as max_profit from fact
join Product
on fact.ProductId=Product.ProductId
Group by fact.ProductId,Product_Type


--21. Create a stored procedure to fetch the result according to the product type from Product Table.

create procedure byprodtype @pt varchar(50) --no brackets 
as
begin
    select * from product
	where product_type=@pt 
end

exec byprodtype 'Tea' --no brackets



--22. Write a query by creating a condition in which if the total expenses is lessthan 60 then it is a profit or else loss.

select *,
       case 
	      when total_expenses<60 then 'profit'
	      else 'loss'
	   end as porf
from fact


--(IMPORTANT) 23. Give the total weekly sales value with the date and product IDdetails. Use roll-up to pull the data in hierarchical order.
select
     datepart(week,date) as weekno,
	 productid,
	 sum(sales) as totalweeksales
from fact
group by rollup(datepart(week,date), productid);


----24. Apply union and intersection operator on the tables which consist of attribute area code.

select area_code from fact --in union, intersect and except operators, you can not have unequal no. of columns in either table so only taking area_code column
union
select area_code from location
order by area_code asc


select area_code from fact
intersect
select area_code from location
order by area_code asc


--25. Create a user-defined function for the product table to fetch a particular product type based upon the user’s preference.

create function userchoice(@ptype varchar(50)) --functions have brackets
returns table
as
return (select*from product where product_type=@ptype)

select * from userchoice('Espresso')


--26. Change the product type from coffee to tea where product IDis 1 and undo it.
select * from Product

begin transaction

update product
set product_type='tea'
where productid=1 and product_type = 'coffee'

rollback


--27. Display the date, product ID and sales where total expenses are between 100 to 200.
select
     date,
	 productid,
	 sales
from fact
where total_expenses between 100 and 200


--28. Delete the records in the Product Table for regular type.
select * from product

begin transaction

delete from product --dont write update keyword when using delete, its either update or delete
where type='Regular'

rollback


--29. Display the ASCII value of the fifth character from the column Product

select product, ascii(substring(product,5,1)) as fifth_char_ascii from product --ascii fucntion shows ascii code of 5th character. 5 indicates from 5th char, 1 indicates that 1 character's ascii is displayed, that starts at 5th character..


